import { MaterialPrice } from '../types/price';

export const INITIAL_PRICES: MaterialPrice[] = [
  {
    id: 'pcb',
    material: 'Printed Circuit Board (PCB)',
    category: 'Electronics',
    price_per_kg: 320,
    market_min: 290,
    market_max: 340,
    trend: 'up',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Computer, telecom & motherboard circuit scrap containing gold/copper pins.',
    safetyNote: 'Avoid acid leaching or open burning of circuit board solder.',
    icon: 'Cpu',
  },
  {
    id: 'cable',
    material: 'Copper Cable & Wires',
    category: 'Metals',
    price_per_kg: 610,
    market_min: 500,
    market_max: 650,
    trend: 'up',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Insulated & heavy-gauge copper wiring, power cords, and transformer cables.',
    safetyNote: 'Do NOT burn cable insulation to extract copper. Use wire stripping tools.',
    icon: 'Zap',
  },
  {
    id: 'battery',
    material: 'Lithium-Ion Battery Pack',
    category: 'Batteries',
    price_per_kg: 95,
    market_min: 70,
    market_max: 110,
    trend: 'up',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Rechargeable mobile, laptop, electric vehicle & power bank batteries.',
    safetyNote: '⚠️ High Risk! Do not puncture, crush, or expose lithium batteries to fire.',
    icon: 'BatteryCharging',
  },
  {
    id: 'copper',
    material: 'Pure Heavy Copper Scrap',
    category: 'Metals',
    price_per_kg: 715,
    market_min: 650,
    market_max: 780,
    trend: 'up',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Stripped copper winding, busbars, and motor coil copper.',
    safetyNote: 'Store in dry area to prevent oxidation and moisture damage.',
    icon: 'Flame',
  },
  {
    id: 'aluminium',
    material: 'Aluminium Heat Sinks',
    category: 'Metals',
    price_per_kg: 180,
    market_min: 150,
    market_max: 210,
    trend: 'flat',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Computer processor heat sinks, amplifier fins, and casing metal.',
    icon: 'Box',
  },
  {
    id: 'crt',
    material: 'CRT Glass Tube',
    category: 'Display',
    price_per_kg: 45,
    market_min: 30,
    market_max: 55,
    trend: 'down',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Old television & computer monitor cathode ray display glass.',
    safetyNote: 'Handle with thick leather gloves. Implosion hazard if glass ruptures.',
    icon: 'Tv',
  },
  {
    id: 'lcd',
    material: 'LCD / LED Display Panel',
    category: 'Display',
    price_per_kg: 180,
    market_min: 140,
    market_max: 200,
    trend: 'flat',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Flat panel monitor screens, TV displays, and laptop screens.',
    icon: 'Monitor',
  },
  {
    id: 'motor',
    material: 'Electric Motor & Compressor',
    category: 'Motors',
    price_per_kg: 240,
    market_min: 210,
    market_max: 270,
    trend: 'up',
    unit: '₹/kg',
    updated_at: 'Today, 6:00 PM',
    description: 'Washing machine motors, fridge compressors, and fan stators.',
    icon: 'Cog',
  },
];

export async function fetchPrices(location: string = 'Bengaluru'): Promise<MaterialPrice[]> {
  // In future: GET /api/v1/prices?location=${location}
  return Promise.resolve(INITIAL_PRICES);
}
